apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: payment-service
  template:
    metadata:
      labels:
        app: payment-service
    spec:
      containers:
      - name: payment-service
        image: food-ordering-payment-service:latest
        ports:
        - containerPort: 3008
        env:
        - name: PORT
          value: "3008"
        - name: MONGODB_URI
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: mongodb-uri
        - name: STRIPE_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: stripe-publishable-key
        - name: STRIPE_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: stripe-secret-key
        - name: STRIPE_WEBHOOK_SECRET
          valueFrom:
            secretKeyRef:
              name: app-secrets
              key: stripe-webhook-secret
        - name: AUTH_SERVICE_URL
          value: "http://auth-service:3002"
        - name: ORDER_SERVICE_URL
          value: "http://order-service:3003"
        - name: NOTIFICATION_SERVICE_URL
          value: "http://notification-service:3006"
        - name: PAYMENT_RETURN_URL
          value: "http://localhost:3000/payment/return"
---
apiVersion: v1
kind: Service
metadata:
  name: payment-service
spec:
  selector:
    app: payment-service
  ports:
  - port: 3008
    targetPort: 3008
  type: ClusterIP
